name: GeoIP

on:
  schedule:
    - cron: '28 13 7 * *'
  workflow_dispatch:

jobs:
  build:
    name: Cache GeoIP database
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Fetch GeoIP from ip2location.
        run: ./fetch-geoip.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP
          tag_name: monthly
          token: ${{ secrets.GEOIP_TOKEN }}
