name: GeoIP

on:
  schedule:
    - cron: '28 13 7 * *'
  workflow_dispatch:

jobs:
  download:
    name: Cache GeoIP database
    runs-on: ubuntu-latest
    steps:
     - name: Clone repository
       uses: actions/checkout@v2

     - name: Fetch GeoIP from ip2location.
       run: ./fetch-geoip.sh

     - name: Upload release asset
       uses: cb80/pubrel@latest
       with:
         replace: latest
         token: ${{ secrets.GEOIP_TOKEN }}
         files: IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP
