name: GeoIP

on:
  schedule:
    - cron: '28 13 7 * *'
  workflow_dispatch:

jobs:
  build:
    name: Cache GeoIP database
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Fetch GeoIP from ip2location.
        id: wait-for-fetch
        run: ./fetch-geoip.sh

      - name: Wait for download.
        if: steps.wait-for-fetch.outputs.conclusion == 'success'
        with:
          token: ${{ secrets.GEOIP_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP
          tag_name: monthly
          repository: OpenRA/GeoIP-Database
          token: ${{ secrets.GEOIP_TOKEN }}
