name: GeoIP

on:
  schedule:
    - cron: '28 13 7 * *'
  workflow_dispatch:

jobs:
  download:
    name: Cache GeoIP Database
    runs-on: ubuntu-latest
    steps:
     - name: Clone Repository
       uses: actions/checkout@v4

     - name: Fetch GeoIP Database
       run: ./fetch-geoip.sh

     - name: Upload Release Asset
       env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       shell: bash
       run: |
          gh release delete-asset monthly IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP --yes
          gh release upload monthly IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP
